package com.woniu.pojo;
// Generated 2019-12-17 16:59:59 by Hibernate Tools 5.4.7.Final

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer rid;
	private String rname;

	public Role() {
	}

	public Role(String rname) {
		this.rname = rname;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

}
